import { apiClient } from '@api/client';
import type { ApiSuccessResponse, PaginatedResult } from '@api/types';
import type {
    AssignShipmentPayload,
    BackendShipment,
    CreateShipmentPayload,
    QuoteShipmentPayload,
    ShipmentQuote,
    ShipmentStatusHistoryEntry,
} from '../types';

// One-to-one with kalanabhaBackend/src/modules/shipments/controllers/shipments.controller.ts

// `idempotencyKey` is optional and generated by the caller once per submit
// attempt (see addOrders.tsx) — sent as `Idempotency-Key` so a network
// retry or double-tap on the same attempt can't create two shipments; the
// backend's IdempotencyInterceptor replays the first response instead.
export const createShipment = async (
    payload: CreateShipmentPayload,
    idempotencyKey?: string,
): Promise<BackendShipment> => {
    const { data } = await apiClient.post<ApiSuccessResponse<BackendShipment>>('/shipments', payload, {
        headers: idempotencyKey ? { 'Idempotency-Key': idempotencyKey } : undefined,
    });
    return data.data;
};

export const quoteShipment = async (payload: QuoteShipmentPayload): Promise<ShipmentQuote> => {
    const { data } = await apiClient.post<ApiSuccessResponse<ShipmentQuote>>('/shipments/quote', payload);
    return data.data;
};

// Active (SEARCHING/ACCEPTED/IN_TRANSIT) shipments for the logged-in customer.
export const getMyShipments = async (): Promise<BackendShipment[]> => {
    const { data } = await apiClient.get<ApiSuccessResponse<BackendShipment[]>>('/shipments/mine');
    return data.data;
};

// Every shipment this customer has ever made, any status — powers
// Profile.tsx's real "Total Shipments"/"Delivered" stats and the
// Transactions History screen (each shipment's price/paymentMode IS the
// transaction; there's no separate Payment/Invoice model on the backend).
export const getMyShipmentHistory = async (): Promise<BackendShipment[]> => {
    const { data } = await apiClient.get<ApiSuccessResponse<BackendShipment[]>>('/shipments/mine/history');
    return data.data;
};

// Pool of unassigned shipments — driver app's "available orders" list.
export const getSearchingShipments = async (): Promise<BackendShipment[]> => {
    const { data } = await apiClient.get<ApiSuccessResponse<BackendShipment[]>>('/shipments/searching');
    return data.data;
};

// driver only — every shipment assigned to the logged-in driver, any
// status (accepted/in_transit/delivered/cancelled). The driver-scoped
// equivalent of getMyShipments above; used for both "my active delivery"
// (chat entry point) and trip history.
export const getMyShipmentsAsDriver = async (): Promise<BackendShipment[]> => {
    const { data } = await apiClient.get<ApiSuccessResponse<BackendShipment[]>>('/shipments/driver/mine');
    return data.data;
};

// admin/dispatcher only — GET /shipments/admin is now paginated (was a
// bare, unbounded array); defaults to a generous first page since no
// mobile screen currently exposes pagination controls for this list.
export const getAllShipmentsForAdmin = async (
    page = 1,
    limit = 100,
): Promise<PaginatedResult<BackendShipment>> => {
    const { data } = await apiClient.get<ApiSuccessResponse<PaginatedResult<BackendShipment>>>(
        '/shipments/admin',
        { params: { page, limit } },
    );
    return data.data;
};

export const getShipmentById = async (id: string): Promise<BackendShipment> => {
    const { data } = await apiClient.get<ApiSuccessResponse<BackendShipment>>(`/shipments/${id}`);
    return data.data;
};

// One real row per real status transition (kalanabhaBackend's
// ShipmentStatusHistory model) — ShipmentDetailsScreen's Tracking Timeline
// reads this instead of a fabricated 'placed'/'picked'/'in-transit' guess,
// so it shows real timestamps and never claims a step happened that
// didn't (same ownership check as getShipmentById).
export const getShipmentHistory = async (id: string): Promise<ShipmentStatusHistoryEntry[]> => {
    const { data } = await apiClient.get<ApiSuccessResponse<ShipmentStatusHistoryEntry[]>>(`/shipments/${id}/history`);
    return data.data;
};

// driver only
export const acceptShipment = async (id: string): Promise<BackendShipment> => {
    const { data } = await apiClient.post<ApiSuccessResponse<BackendShipment>>(`/shipments/${id}/accept`);
    return data.data;
};

// admin/dispatcher only
export const assignShipment = async (id: string, payload: AssignShipmentPayload): Promise<BackendShipment> => {
    const { data } = await apiClient.post<ApiSuccessResponse<BackendShipment>>(`/shipments/${id}/assign`, payload);
    return data.data;
};

// driver only
export const startDelivery = async (id: string): Promise<BackendShipment> => {
    const { data } = await apiClient.post<ApiSuccessResponse<BackendShipment>>(`/shipments/${id}/start`);
    return data.data;
};

// driver only — otp is the 4-digit delivery code the customer reads out,
// verified server-side against the real Shipment.deliveryOtp.
export const completeDelivery = async (id: string, otp: string): Promise<BackendShipment> => {
    const { data } = await apiClient.post<ApiSuccessResponse<BackendShipment>>(`/shipments/${id}/complete`, { otp });
    return data.data;
};

// customer (owner) or admin/dispatcher
export const cancelShipment = async (id: string): Promise<BackendShipment> => {
    const { data } = await apiClient.post<ApiSuccessResponse<BackendShipment>>(`/shipments/${id}/cancel`);
    return data.data;
};

// Proof of Delivery — driver only, must be the shipment's own assigned
// driver (kalanabhaBackend enforces this, not just this screen). Same
// multipart shape driverDocuments.api.ts's upload already uses.
export const uploadShipmentPod = async (id: string, fileUri: string, fileName: string, mimeType: string): Promise<BackendShipment> => {
    const form = new FormData();
    form.append('file', { uri: fileUri, name: fileName, type: mimeType } as any);

    const { data } = await apiClient.post<ApiSuccessResponse<BackendShipment>>(`/shipments/${id}/pod`, form, {
        headers: { 'Content-Type': 'multipart/form-data' },
    });
    return data.data;
};
